name = "tradingview-bot"
main = "worker.js"
compatibility_date = "2026-04-28"

[triggers]
crons = ["0 7 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "wavescout_db"
database_id = "550e7c98-5757-451d-b0ea-5c8f374c53b1"

[observability.logs]
enabled = true
